language: ruby
before_install: rm Gemfile.lock || true
rvm:
- 2.1.3
script:
- bundle exec rake test
env:
  matrix:
  - PUPPET_VERSION="~> 3.7.3"
  - PUPPET_VERSION="~> 3.7.3" FUTURE_PARSER=yes
  global:
  - secure: fbMWa5wQb7Jc44Dy71ouoPoN4ePhKgIvFzjyRhgDDGa1LzMwKF3XBzHDe76V3ArcRjx70kuHqDEFWPpX0tas7qWo33+MjM9rO+Gh0fqrmqA0ufwqJJcv/fSRUeFg5wPgPxXcAxu0VcOV3nm8U+x7Rmap5+PVvRNBDKSuF1vGRxQ=
  - secure: RrDpmHvF1PD+kOitCL0IB1UBXWXg50ZJ0qVSdvf5A1EsE9C88rw3nOeJfKKMPCjgFFt+JzAZWLuhMVnBuoO9j5eOnmMxFtmtNWC/QKW8LwTfMlBUobP8bUiBW8Z9cxAtLxbFgBcKLwLY5jL1H1wNQWW3vMLonnMgFEeGOpXibRg=
after_success:
- curl -o travis_after_all.py https://raw.githubusercontent.com/dmakhno/travis_after_all/b7172bca92d6dcfcec2a0eacdf14eb5f3a1ad627/travis_after_all.py
- python travis_after_all.py
- export $(cat .to_export_back)
- "./travis/deploy.sh"
after_failure:
- python travis_after_all.py
- export $(cat .to_export_back)
- |
  if [ "$BUILD_LEADER" = "YES" ]; then
    if [ "$BUILD_AGGREGATE_STATUS" = "others_failed" ]; then
      echo "All Failed"
    else
      echo "Some Failed"
    fi
  fi
after_script:
- echo leader=$BUILD_LEADER status=$BUILD_AGGREGATE_STATUS
