language: ruby
before_install: rm Gemfile.lock || true
rvm:
- 2.1.3
script:
- bundle exec rake test
env:
  matrix:
  - PUPPET_VERSION="~> 3.7.3"
  - PUPPET_VERSION="~> 3.7.3" FUTURE_PARSER=yes
  global:
  - secure: jrApKcbe1S+UrhiH24Kk+P1fwgTkPMPap+2U77lb3VBtXmR3mAhdBoMMbmC4y+3PADhIMRukzZ2eyQP+Ces/Qwo6rSZPDDc9jAjvToNzlaxNxkyHaO5aZAXyGJRlFaLFerfPiH0A3HEERKAwJOjB0MmMT9CILRf+Wt0N3kFBRbw=
  - secure: KDtdQRoHvkr4e/tYk3wR+H/lr1DwUdQ5538jJQnpu49UQDXTVRxWQsUCkE+k8ADRKp8dA4q+9vqLBGW+nUgUhPcH71Drdmhyq4x4edbFXNjJ1tfKvira29KpdgseaApKEaYXQh4Gr+zM6GYKc7/OXSWLnS/vd2pr5qLvePWB6Wc=
after_success:
- curl -o travis_after_all.py https://raw.githubusercontent.com/dmakhno/travis_after_all/b7172bca92d6dcfcec2a0eacdf14eb5f3a1ad627/travis_after_all.py
- python travis_after_all.py
- export $(cat .to_export_back)
- "./travis/deploy.sh"
after_failure:
- python travis_after_all.py
- export $(cat .to_export_back)
- |
  if [ "$BUILD_LEADER" = "YES" ]; then
    if [ "$BUILD_AGGREGATE_STATUS" = "others_failed" ]; then
      echo "All Failed"
    else
      echo "Some Failed"
    fi
  fi
after_script:
- echo leader=$BUILD_LEADER status=$BUILD_AGGREGATE_STATUS
